// src/app/layout.tsx
import ClientLayout from "./ClientLayout";
import Hero from "./components/hero/Hero";
import Properties from "./components/properties/Properties";
import "./globals.css";

export const metadata = {
  title: "React (news, help, install, ...)",
  description: "Generated by create next app",
};

export default function RootLayout({
  children,
}: Readonly<{
  children: React.ReactNode;
}>) {
  return (
    <html lang="fr">
      <body>
        <ClientLayout>
          <main className="main">
            <Hero />
            <Properties />
          </main>
        </ClientLayout>
      </body>
    </html>
  );
}
