// src/app/layout.tsx
import "./globals.css";

export const metadata = {
  title: "React (news, help, install, ...)",
  description: "Generated by create next app",
};

export default function RootLayout({
  children,
}: Readonly<{
  children: React.ReactNode;
}>) {
  return (
    <html lang="fr">
      <body>{children}</body>
    </html>
  );
}
